################# System ################# 
sys.max_threads=4

################# Logging ################
log.level=INFO
log.path=/var/log/maestro.log

################## Data ##################
data.dir=/var/lib/maestro/
data.type=json

data.spots.currency=SEK
data.spots.dir=/var/lib/maestro/spots/

data.weather.dir=/var/lib/maestro/spots/
