################# System ################# 
sys.max_threads=4

################# Logging ################
log.level=INFO
log.path=/var/log/maestro.log

################## Data ##################
data.dir=/var/lib/maestro
data.calcs.dir=/var/lib/maestro/calcs

################ Facility ################
facility.conf.dir=/etc/maestro/facility
