################ Facility ################
# Mock facility used to keep report generation working when real facility data
# is unavailable.
name=home

currency=SEK
price_class=3

latitude=59.32835192604205
longitude=18.28451894076166
